[project]
name = "hf-explore"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "LUCAS_FIGUEROA", email = "lucas@heliosgroup.ai" }
]
requires-python = ">=3.12"
dependencies = [
    "python-docx>=1.2.0",
    "streamlit>=1.65.0",
    "torch>=2.14.1",
    "transformers>=5.19.0",
]

[project.scripts]
hf-explore = "hf_explore:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
